const actionTypes = {
    OPEN_ADD_USER_DIALOG: 'OPEN_ADD_USER_DIALOG',
    OPEN_EDIT_USER_DIALOG: 'OPEN_EDIT_USER_DIALOG',
    CLOSE_USER_DIALOG: 'CLOSE_USER_DIALOG',
    UPDATE_USERNAME_FIELD: 'UPDATE_USERNAME_FIELD',
    UPDATE_TIMEOUT_FIELD: 'UPDATE_TIMEOUT_FIELD',
    UPDATE_PASSWORD_FIELD: 'UPDATE_PASSWORD_FIELD',
    UPDATE_CONFIRM_PASSWORD_FIELD: 'UPDATE_CONFIRM_PASSWORD_FIELD',
    ADD_USER: 'ADD_USER',
    SAVE_USER: 'SAVE_USER',

    OPEN_ADD_CUSTOMER_DIALOG: 'OPEN_ADD_CUSTOMER_DIALOG',
    OPEN_EDIT_CUSTOMER_DIALOG: 'OPEN_EDIT_CUSTOMER_DIALOG',
    CLOSE_CUSTOMER_DIALOG: 'CLOSE_CUSTOMER_DIALOG',
    UPDATE_FIRSTNAME_FIELD: 'UPDATE_FIRSTNAME_FIELD',
    UPDATE_LASTNAME_FIELD: 'UPDATE_LASTNAME_FIELD',
    ADD_CUSTOMER: 'ADD_CUSTOMER',
    SAVE_CUSTOMER: 'SAVE_CUSTOMER',

    OPEN_ADD_SUPPLIER_DIALOG: 'OPEN_ADD_SUPPLIER_DIALOG',
    OPEN_EDIT_SUPPLIER_DIALOG: 'OPEN_EDIT_SUPPLIER_DIALOG',
    CLOSE_SUPPLIER_DIALOG: 'CLOSE_SUPPLIER_DIALOG',
    UPDATE_SUPPLIER_NAME_FIELD: 'UPDATE_SUPPLIER_NAME_FIELD',
    ADD_SUPPLIER: 'ADD_SUPPLIER',
    SAVE_SUPPLIER: 'SAVE_SUPPLIER',

    OPEN_ADD_BRAND_DIALOG: 'OPEN_ADD_BRAND_DIALOG',
    OPEN_EDIT_BRAND_DIALOG: 'OPEN_EDIT_BRAND_DIALOG',
    CLOSE_BRAND_DIALOG: 'CLOSE_BRAND_DIALOG',
    UPDATE_BRAND_NAME_FIELD: 'UPDATE_BRAND_NAME_FIELD',
    ADD_BRAND: 'ADD_BRAND',
    SAVE_BRAND: 'SAVE_BRAND',

    ENABLE_EDITABLE: 'ENABLE_EDITABLE',
    UPDATE_CONTACT_FIELD: 'UPDATE_CONTACT_FIELD',

    CHANGE_TAB_SUPPLIER_RECORD: 'CHANGE_TAB_SUPPLIER_RECORD',
    CHANGE_TAB_BRAND_RECORD: 'CHANGE_TAB_BRAND_RECORD',
    CHANGE_TAB_ITEM_RECORD: 'CHANGE_TAB_ITEM_RECORD'
};

export default actionTypes;