const actionTypes = {
    OPEN_ADD_USER_DIALOG: 'OPEN_ADD_USER_DIALOG',
    OPEN_EDIT_USER_DIALOG: 'OPEN_EDIT_USER_DIALOG',
    CLOSE_USER_DIALOG: 'CLOSE_USER_DIALOG',
    ENABLE_EDITABLE: 'ENABLE_EDITABLE',
    UPDATE_USERNAME_FIELD: 'UPDATE_USERNAME_FIELD',
    UPDATE_TIMEOUT_FIELD: 'UPDATE_TIMEOUT_FIELD',
    UPDATE_PASSWORD_FIELD: 'UPDATE_PASSWORD_FIELD',
    UPDATE_CONFIRM_PASSWORD_FIELD: 'UPDATE_CONFIRM_PASSWORD_FIELD',

    OPEN_ADD_CUSTOMER_DIALOG: 'OPEN_ADD_CUSTOMER_DIALOG',
    OPEN_EDIT_CUSTOMER_DIALOG: 'OPEN_EDIT_CUSTOMER_DIALOG'
};

export default actionTypes;