const pageOptions = {
    ADMIN_MAIN_MENU: "ADMIN_MAIN_MENU",
    ADMIN_USER_RECORDS: 'ADMIN_USER_RECORDS',
    ADMIN_CUSTOMER_RECORDS: 'ADMIN_CUSTOMER_RECORDS',
    ADMIN_PRODUCTS_PAGE: 'ADMIN_PRODUCTS_PAGE',
    ADMIN_STOCKING_PAGE: 'ADMIN_STOCKING_PAGE',
    ADMIN_RECORDS_HISTORY: 'ADMIN_RECORDS_HISTORY'
}

export default pageOptions;