const pageOptions = {
    ADMIN_MAIN_MENU: 'ADMIN_MAIN_MENU',
    ADMIN_USER_RECORDS: 'ADMIN_USER_RECORDS',
    ADMIN_CUSTOMER_RECORDS: 'ADMIN_CUSTOMER_RECORDS',
    ADMIN_PRODUCTS_PAGE: 'ADMIN_PRODUCTS_PAGE',
    ADMIN_STOCKING_PAGE: 'ADMIN_STOCKING_PAGE',
    ADMIN_RECORDS_HISTORY: 'ADMIN_RECORDS_HISTORY',

    USER_MAIN_MENU: 'USER_MAIN_MENU',
    USER_SHOPPING_PAGE: 'USER_SHOPPING_PAGE'
}

export default pageOptions;