const tabOptions = {
    SUPPLIER_RECORD: "SUPPLIER_RECORD",
    BRAND_RECORD: 'BRAND_RECORD',
    ITEM_RECORD: 'ITEM_RECORD',
    SALES_RECORD: 'SALES_RECORD',
    CREDIT_RECORD: 'CREDIT_RECORD',
    STOCK_RECORD: 'STOCK_RECORD'
}

export default tabOptions;